### PR TITLE
Fixed score confirm bypass

### LINKED ISSUE #239: Can bypass score confirmation
If the game is in sudden death, and the refbox is set to not track scorer cap numbers, then pressing a score button (score black, score white) will immediately end the game with that score applied, without asking for confirmation

### PR DESCRIPTION
**Pull request by elsald**
Changed AddNewScore message to check if in Sudden Death and end game, then change app state to confirm scores. Otherwise it just adds a score and goes back to the main page. 

Fixes #239

### CODE REVIEW

File: refbox/src/app/mod.rs [hunk 1]
```diff
@@ -961,10 +961,16 @@ impl Application for RefBoxApp {
                 } else {
                     let mut tm = self.tm.lock().unwrap();
                     let now = Instant::now();
-                    tm.add_score(color, 0, now);
-                    let snapshot = tm.generate_snapshot(now).unwrap(); // TODO: Remove this unwrap
-                    std::mem::drop(tm);
-                    self.apply_snapshot(snapshot);
```
Comment (TristanDebrunner) [inline refbox/src/app/mod.rs:967]: These lines are important ans cannot be skipped. Without them the score displayed will be incorrect until the next change in the time

File: refbox/src/app/mod.rs [hunk 2]
```diff
@@ -961,10 +961,16 @@ impl Application for RefBoxApp {
...
+                        let mut scores = tm.get_scores();
+                        scores[color] = scores[color].saturating_add(1);
+
+                        self.app_state = AppState::ConfirmScores(scores);
+                    } else {
+                        tm.add_score(color, 0, now);
+                        self.app_state = AppState::MainPage;
+                    }
                 }
             }
```
Comment (TristanDebrunner) [inline refbox/src/app/mod.rs:975]: The `trace!("AppState changed to {:?}", self.app_state);` line above should be moved between these two lines so that a change in `self.app_state` is always logged

**Review by TristanDebrunner — CHANGES_REQUESTED** [review]

**Review by TristanDebrunner — APPROVED** [review]
